#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
cp -r ../rotor rotor
cp -r ../stator stator
cp -r ../simple simple
mergeMeshes -overwrite stator/ rotor/
mergeMeshes -overwrite simple/ rotor/
mv stator/ cylinder_AMI/
#cd cylinder_AMI/
#runApplication topoSet
#paraFoam

# ----------------------------------------------------------------- end-of-file
