#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication topoSet
cp -r 0_org/* 0/
runApplication decomposePar
runParallel `getApplication` 8
runApplication reconstructPar
paraFoam

# ----------------------------------------------------------------- end-of-file
