#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication topoSet
cp -r ../stator/constant/polyMesh/* ./constant/polyMesh/

# ----------------------------------------------------------------- end-of-file
